// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "raverte": {
    "Raverte": {
      /**
       * GetChartOnlyMode
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "GetChartOnlyMode": () => {
        return window.go.raverte.Raverte.GetChartOnlyMode();
      },
      /**
       * LoadProfile
       * @returns {Promise<void>} 
       */
      "LoadProfile": () => {
        return window.go.raverte.Raverte.LoadProfile();
      },
    },
  },

};
export default go;
