// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChartOnlyMode():Promise<boolean>;

export function LoadProfile():Promise<Error>;

export function UnlockKeys(arg1:string):Promise<Error>;
