// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChartOnlyMode() {
  return window['go']['raverte']['Raverte']['GetChartOnlyMode']();
}

export function LoadProfile() {
  return window['go']['raverte']['Raverte']['LoadProfile']();
}

export function UnlockKeys(arg1) {
  return window['go']['raverte']['Raverte']['UnlockKeys'](arg1);
}
